application: b1bl10t3c4
version: 2c
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /css
  static_dir: css

- url: /js
  static_dir: js
  
- url: /img
  static_dir: img

- url: /fonts
  static_dir: fonts

- url: /api
  static_files: api.html
  upload: api.html

- url: /api/.*
  script: api.app

- url: /contador
  static_files: contador.html
  upload: contador.html

- url: (.*)/
  static_files: index.html
  upload: index.html

libraries:
- name: webapp2
  version: "2.5.2"
